<?php
/**
 * Mediasharex
 */
class Mediasharex_Api_User extends Zikula_AbstractApi
{

     /**
     * Get categories
     *
     */
    public function getMediaCats()
    {
        // Security check
        if (!SecurityUtil::checkPermission('Mediasharex::', '::', ACCESS_READ)) {
            return LogUtil::registerPermissionError();
        }
        
        $all['catreg'] = CategoryRegistryUtil::getRegisteredModuleCategories('Mediasharex', 'mediasharex_media');
               
        $all = CategoryUtil::getSubCategories($all['catreg']['Cat']);
        

        // Return the output that has been generated by this function
        return $all;
    }	

     /**
     * Get categories
     *
     */
    public function getAlbumaCats()
    {
        // Security check
        if (!SecurityUtil::checkPermission('Mediasharex::', '::', ACCESS_READ)) {
            return LogUtil::registerPermissionError();
        }
        
        $all['catreg'] = CategoryRegistryUtil::getRegisteredModuleCategories('Mediasharex', 'mediasharex_albums');
               
        $all = CategoryUtil::getSubCategories($all['catreg']['Cat']);
        

        // Return the output that has been generated by this function
        return $all;
    }
	
	
     /**
     * Get categories
     *
     */
    public function getUserAlbum()
    {
        // Security check
        if (!SecurityUtil::checkPermission('Mediasharex::', '::', ACCESS_READ)) {
            return LogUtil::registerPermissionError();
        }
        
		$albums_userAlbum_Enabled = $this->getVar('albums_userAlbum_Enabled',false);
		$albums_userAlbum_HomeAlbum = $this->getVar('albums_userAlbum_HomeAlbum',false);
 		if(!$albums_userAlbum_Enabled || !$albums_userAlbum_HomeAlbum){		
		    return false;			
		}

		$user = UserUtil::getVar('uid');
 		if($user == -1){		
		    return false;			
		}
	
		//Get albums		
		$albums = new Mediasharex_Manager_Albums();
		$albums->setAuthor($user);
		$albums->setParentalbum($albums_userAlbum_HomeAlbum);		
		$albums_array = $albums->getAll();	
       
        // Return user album object
        return $albums_array[0];
    }
		
   
}
