<?php
/**
 * Mediasharex
 */
class Mediasharex_Api_User extends Zikula_AbstractApi
{

     /**
     * Get categories
     *
     */
    public function getMediaCats()
    {
        // Security check
        if (!SecurityUtil::checkPermission('Mediasharex::', '::', ACCESS_READ)) {
            return LogUtil::registerPermissionError();
        }
        
        $all['catreg'] = CategoryRegistryUtil::getRegisteredModuleCategories('Mediasharex', 'mediasharex_media');
               
        $all = CategoryUtil::getSubCategories($all['catreg']['Cat']);
        

        // Return the output that has been generated by this function
        return $all;
    }	

     /**
     * Get categories
     *
     */
    public function getAlbumaCats()
    {
        // Security check
        if (!SecurityUtil::checkPermission('Mediasharex::', '::', ACCESS_READ)) {
            return LogUtil::registerPermissionError();
        }
        
        $all['catreg'] = CategoryRegistryUtil::getRegisteredModuleCategories('Mediasharex', 'mediasharex_albums');
               
        $all = CategoryUtil::getSubCategories($all['catreg']['Cat']);
        

        // Return the output that has been generated by this function
        return $all;
    }
		
   
}
